import { Sidebar } from "@/components";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create New Post",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="grid grid-cols-[300px_1fr] h-screen max-h-screen">
      <Sidebar />
      <div className="bg-zinc-800 h-screen max-h-screen overflow-auto py-6">
        {children}
      </div>
    </div>
  );
}
